### ISSUE TITLE
ReactDom.render is not a function error with version 0.3.0

### ISSUE THREAD

**Issue by mdurling** [fathyb/parcel-plugin-typescript#7]
I am getting the following error after upgrading to v0.3.0; everything works fine using v0.2.3
```
fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:17886 Uncaught TypeError: ReactDOM.render is not a function
    at Object.require.1.react (fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:17886)
    at newRequire (fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:41)
    at require.8 (fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:66)
    at fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:71
require.1.react @ fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:17886
newRequire @ fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:41
require.8 @ fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:66
(anonymous) @ fee6b0bd49a5e8e9775e4eb5fd789a0f.js:sourcemap:71
```

**Comment by fathyb** [comment]
Are you importing React-DOM using `import ReactDOM from 'react-dom`? If not please tell how you import it.

I'm able to reproduce the error (using `import ReactDOM from 'react-dom`) on all versions, are you sure you only upgraded the plugin? You should import React-DOM using `import * as ReactDOM from 'react-dom'` because it is exported as a CommonJS module. Webpack does interop `default` but I think Parcel does not.

If you have a reproduction repository it could help.

**Comment by mdurling** [comment]
I'm targeting ES5/commonjs in tsconfig so I have to use `import * as ReactDOM from 'react-dom'`. Check out `https://github.com/leason/tekata-web` It's just a hello world app, but you should be able to see the different results between versions 0.2.4, 0.2.5-next, and 0.3.0.

**Comment by fathyb** [comment]
Thanks for the repo, I can reproduce it now. The issue seems to be that modules are mixed up and I don't know why yet. I'm going to fix it but I don't have much time now, I'll ping you in this issue when it's resolved. In the meantime, if you don't use Angular, you can fallback to `0.2.5-next`, I'll publish it as `0.2.5` when I get on my computer.

**Comment by mdurling** [comment]
Sounds good. Thanks!

**Comment by fathyb** [comment]
I've just released `0.2.5`, same as `0.2.5-next` and tagged as `latest`. I found the bug, it's due to a dependency conflict between Parcel and the plugin. This dependencies are only required for Angular so I'm going to remove all the Angular specifics from here and move them to a plugin on it's own, hopefully it will bring more stability to the plugin.

**Comment by mdurling** [comment]
I use React, so excluding Angular dependencies sounds outstanding!

**Comment by fathyb** [comment]
The Angular support has been fully moved to another plugin and `parcel-plugin-typescript@0.4.0-next.11` has been published accordingly. If you confirm it works for you I'll release it as `0.4.0`.

**Comment by mdurling** [comment]
parcel-plugin-typescript@0.4.0-next.11 seems to work fine. LMK when the official 0.4.0 release is available. Thanks!

**Comment by fathyb** [comment]
[`0.4.0` is released](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#040-2018-01-05) 🎉

**Comment by mdurling** [comment]
@fathyb Thank you ... I have already deployed it.
